source 'https://rubygems.org'
gem 'browbeat', git: 'git://github.com/NYULibraries/browbeat_old.git', branch: 'gem'
gem 'pry'
gem 'figs'
gem 'phantomjs'
gem 'poltergeist'
gem 'capybara'
gem 'selenium-webdriver'
